import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

interface RootLayoutProps {
  readonly children: React.ReactNode;
}

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Noxen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="es">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
